### ISSUE TITLE
schema.json

### ISSUE THREAD

**Issue by joenatan** [odoogap/vuestorefront#3]
is there a way to create/download the schema.json?
It would be great for other frontend libraries.

**Comment by dduarte-odoogap** [comment]
@joenatan not sure what you mean, but this graphQL API can be used by other frontend libraries, there is no restriction at all

**Comment by joenatan** [comment]
this is embarrassing now 🥲 ....
I wanted to generate the hooks using codegen and react-query. After a typo correction.... it works.
