### ISSUE TITLE
Odoo 11 branch

### ISSUE THREAD

**Issue by seyuf** [odoogap/vuestorefront#6]
Hi there,

I guess the branch for odoo 11 is not ready yet? As im having a hard time making it work.

Regards

**Comment by dduarte-odoogap** [comment]
hi @seyuf we did used it for some projects but heavily customised because v11 doesn't have a complete multi website feature, so we do have some code there but we don't consider that ready for usage, just a starting point for anyone that wants to complete the work

**Comment by seyuf** [comment]
Hun i see, thanks for the reply :pray:
